server:
  port: 8080

spring:
  thymeleaf.mode: LEGACYHTML5
  datasource:
    url: jdbc:h2:mem:todolist;DB_CLOSE_ON_EXIT=FALSE;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    show_sql: true
#    use_sql_comments: true
#    format_sql: true
  h2.console:
    enabled: true
    path: /h2-console
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul