CREATE TABLE IF NOT EXISTS TODO (
	ID VARCHAR(255) NOT NULL AUTO_INCREMENT,
	CONTENT VARCHAR(255) NOT NULL,
	COMP_YN VARCHAR(1) NOT NULL,
	INS_DTM TIMESTAMP NOT NULL,
	UPD_DTM TIMESTAMP,
	CONSTRAINT TODO_PK PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
